using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("Virtual Alt Net")]
[assembly: AssemblyCopyrightAttribute("Copyright © Virtual Alt Net 2009")]
[assembly: AssemblyVersionAttribute("1.0.0.*")]
[assembly: AssemblyFileVersionAttribute("1.0.0.*")]

